name: niagara4
summary: Niagara Framework
description: Niagara IoT Framework
version: "4.13.3.48"

base: core24
grade: devel
confinement: devmode

platforms:
  amd64:

apps:
  niagarad:
    command: bin/niagarad-wrapper
    daemon: simple
    environment:
      LD_LIBRARY_PATH: $SNAP/bin
      HOME: $SNAP_COMMON
    plugs: [network, network-bind]

parts:
  jre:
    plugin: dump
    source: http://pubfs.iotapp.site/n4installer/4.13.3.48/dist/azul-jre-linux-amd64.dist
    source-type: zip
    organize:
      "*": jre/
  deps:
    plugin: nil
    stage-packages:
      - util-linux
  core:
    plugin: dump
    source: http://pubfs.iotapp.site/n4installer/4.13.3.48/dist/nre-core-linux-x64.dist
    source-type: zip
    organize:
      "*": bin/
    stage:
      - -bin/ext/jxbrowser
      - "*"
    override-stage: |
      snapcraftctl stage
      chmod +x bin/*

  config:
    plugin: dump
    source: http://pubfs.iotapp.site/n4installer/4.13.3.48/dist/nre-config-linux-x64.dist
    source-type: zip
    stage:
      - -*.sh
      - -INSTALL
      - -README
      - -META-INF
      - -etc/m2
      - -etc/sources
      - -etc/gradle
      - "*"
  overlay:
    plugin: dump
    source: overlay

layout:
  /etc/niagara:
    bind: $SNAP_COMMON/etc/niagara
  $SNAP/security/licenses:
    bind: $SNAP_COMMON/security/licenses
  $SNAP/modules:
    bind: $SNAP_COMMON/modules
